DROP TABLE COVERAGE_RISK_STG;
DROP TABLE COVERAGE_STG;
DROP TABLE NO_OF_DRIVER_STG;
DROP TABLE NO_OF_VEHI_STG;
DROP TABLE NO_OF_NAME_INSU_STG;
DROP TABLE NO_OF_VIO_STG;
DROP TABLE POLICY_SUMMARY_STG;
COMMIT;
---   POLICY_SUMMARY_STG

CREATE TABLE POLICY_SUMMARY_STG 
(
  POLICYNUMBER VARCHAR2(50) NOT NULL 
, LOB VARCHAR2(20) 
, POLICYSTATUSCD VARCHAR2(50) 
, POLICYFORMCD VARCHAR2(50) 
, TIMEDPOLICYSTATUSCD VARCHAR2(20) 
, TXTYPE VARCHAR2(20) 
, CONTRACTTERMTYPECD VARCHAR2(20) 
, PRODUCTCD VARCHAR2(20) 
, RISKSTATECD VARCHAR2(20) 
, EFFECTIVE DATE 
, EXPIRATION DATE 
, POLICYDETAIL_ID VARCHAR2(20) NOT NULL 
, CURRENTREVISIONIND VARCHAR2(20) 
, DOC_YN CHAR(1 BYTE) DEFAULT 'N' 
, DOC_TYPE CHAR(50) DEFAULT 'NA' 
, CONSTRAINT POLICY_SUMMARY_STG_PK PRIMARY KEY 
  (
    POLICYDETAIL_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX POLICY_SUMMARY_STG_PK ON POLICY_SUMMARY_STG (POLICYDETAIL_ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE INDEX POLICY_SUMMARY_STG_INDEX1 ON POLICY_SUMMARY_STG (POLICYNUMBER ASC, POLICYDETAIL_ID ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;



-- -  COVERAGE_STG
CREATE TABLE COVERAGE_STG 
(
  ID VARCHAR2(50) NOT NULL 
, POLICYDETAIL_ID VARCHAR2(50) 
, COVERAGECD VARCHAR2(50) 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE INDEX COVERAGE_STG_INDEX1 ON COVERAGE_STG (POLICYDETAIL_ID ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE COVERAGE_STG
ADD CONSTRAINT COVERAGE_STG_FK1 FOREIGN KEY
(
  POLICYDETAIL_ID 
)
REFERENCES POLICY_SUMMARY_STG
(
  POLICYDETAIL_ID 
)
ENABLE;


---  COVERAGE_RISK_STG

CREATE TABLE COVERAGE_RISK_STG 
(
  ID VARCHAR2(50) NOT NULL 
, POLICYDETAIL_ID VARCHAR2(50) NOT NULL 
, COVERAGECD VARCHAR2(50) 
, CONSTRAINT COVERAGE_RISK_STG_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE INDEX COVERAGE_RISK_STG_INDEX1 ON COVERAGE_RISK_STG (POLICYDETAIL_ID ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE COVERAGE_RISK_STG
ADD CONSTRAINT COVERAGE_RISK_STG_FK2 FOREIGN KEY
(
  POLICYDETAIL_ID 
)
REFERENCES POLICY_SUMMARY_STG
(
  POLICYDETAIL_ID 
)
ON DELETE CASCADE ENABLE;


 --- NO_OF_DRIVER_STG
CREATE TABLE NO_OF_DRIVER_STG 
(
  POLICYDETAIL_ID VARCHAR2(50) NOT NULL 
, COUNT NUMBER(5, 0) DEFAULT 0 NOT NULL 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE INDEX NO_OF_DRIVER_STG_INDEX1 ON NO_OF_DRIVER_STG (POLICYDETAIL_ID ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE NO_OF_DRIVER_STG
ADD CONSTRAINT NO_OF_DRIVER_STG_UK1 UNIQUE 
(
  POLICYDETAIL_ID 
)
USING INDEX NO_OF_DRIVER_STG_INDEX1
ENABLE;

ALTER TABLE NO_OF_DRIVER_STG
ADD CONSTRAINT NO_OF_DRIVER_STG_FK1 FOREIGN KEY
(
  POLICYDETAIL_ID 
)
REFERENCES POLICY_SUMMARY_STG
(
  POLICYDETAIL_ID 
)
ENABLE;


--NO_OF_VEHI_STG
CREATE TABLE NO_OF_VEHI_STG 
(
  POLICYDETAIL_ID VARCHAR2(50) NOT NULL 
, COUNT NUMBER(5, 0) DEFAULT 0 NOT NULL 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE INDEX NO_OF_VEHI_STG_INDEX1 ON NO_OF_VEHI_STG (POLICYDETAIL_ID ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE NO_OF_VEHI_STG
ADD CONSTRAINT NO_OF_VEHI_STG_UK1 UNIQUE 
(
  POLICYDETAIL_ID 
)
USING INDEX NO_OF_VEHI_STG_INDEX1
ENABLE;

ALTER TABLE NO_OF_VEHI_STG
ADD CONSTRAINT NO_OF_VEHI_STG_FK1 FOREIGN KEY
(
  POLICYDETAIL_ID 
)
REFERENCES POLICY_SUMMARY_STG
(
  POLICYDETAIL_ID 
)
ENABLE;



--NO_OF_NAME_INSU_STG
CREATE TABLE NO_OF_NAME_INSU_STG 
(
  POLICYDETAIL_ID VARCHAR2(50) NOT NULL 
, COUNT NUMBER(5, 0) NOT NULL 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE INDEX NO_OF_NAME_INSU_STG_INDEX1 ON NO_OF_NAME_INSU_STG (POLICYDETAIL_ID ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE NO_OF_NAME_INSU_STG
ADD CONSTRAINT NO_OF_NAME_INSU_STG_UK1 UNIQUE 
(
  POLICYDETAIL_ID 
)
USING INDEX NO_OF_NAME_INSU_STG_INDEX1
ENABLE;

ALTER TABLE NO_OF_NAME_INSU_STG
ADD CONSTRAINT NO_OF_NAME_INSU_STG_FK1 FOREIGN KEY
(
  POLICYDETAIL_ID 
)
REFERENCES POLICY_SUMMARY_STG
(
  POLICYDETAIL_ID 
)
ENABLE;



--NO_OF_VIO_STG
CREATE TABLE NO_OF_VIO_STG 
(
  POLICYDETAIL_ID VARCHAR2(50) NOT NULL 
, COUNT NUMBER(5, 0) NOT NULL 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS;

CREATE INDEX NO_OF_VIO_STG_INDEX1 ON NO_OF_VIO_STG (POLICYDETAIL_ID ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE NO_OF_VIO_STG
ADD CONSTRAINT NO_OF_VIO_STG_UK1 UNIQUE 
(
  POLICYDETAIL_ID 
)
USING INDEX NO_OF_VIO_STG_INDEX1
ENABLE;

ALTER TABLE NO_OF_VIO_STG
ADD CONSTRAINT NO_OF_VIO_STG_FK1 FOREIGN KEY
(
  POLICYDETAIL_ID 
)
REFERENCES POLICY_SUMMARY_STG
(
  POLICYDETAIL_ID 
)
ENABLE;

COMMIT;