var topNav='';
topNav+=' <section>';
topNav+='<nav class="mainTabCtrl clearfix">';
topNav+='	<ul>';
topNav+='		<li id="Policy_Property_Search"><a href="./policyProp">Policy - Property Search</a><span>Policy - Property Search</span></li>';
topNav+='		<li id="Policy_Auto_Search"><a href="./policyAuto">Policy - Auto Search</a><span>Policy - Auto Search</span></li>';
topNav+='		<li id="Policy_Search"><a href="./policySearch">Life - Policy Search</a><span>Life - Policy Search </span></li>';
topNav+='		<li id="Policy_Claim_Search"><a href="./claimSearch">Life - Claim Search</a><span>Life - Claim Search</span></li>';
topNav+='	</ul>';
topNav+='</nav>';
topNav+='   </section>';
document.write(topNav);