var topNav='';
topNav+='<header>';
topNav+='	  <div class="top-blue-nav">'; 
topNav+='	<!--Primary Navigation Menu Start-->';
topNav+='		<div class="container">';
topNav+='	    	<div class="primary-nav">';
topNav+='		<nav>';
topNav+='	  	<ul>';
topNav+='        <li><a href="index"><img src="images/home-icon.png" width="20" height="20" alt=""/> Home</a></li>';
topNav+='        <li><a href="http://www.capgemini.com/about-capgemini" TARGET="_NEW"><img src="images/about-icon.png" width="20" height="20" alt=""/> About Us</a></li>';
topNav+='        <li><a href="http://www.in.capgemini.com/contact-capgemini" TARGET="_NEW"><img src="images/contact-icon.png" width="20" height="20" alt=""/> Contact Us</a></li>';
topNav+='        <li><a href="./logout?logout=true"><img src="images/logout-icon.png" width="20" height="20" alt=""/> Logout</a></li>';
topNav+='      </ul>';
topNav+='    </nav>';
topNav+='  </div>';
topNav+='  <div class="welcome">';
topNav+='    <h5>Welcome</h5>';
topNav+='  </div>';
topNav+='  <div class="clearfloat">&nbsp;</div>';
topNav+='</div>';
topNav+='<!--Primary Navigation Menu Ends-->'; 
topNav+='</div>';
topNav+='<div class="navigation">';
topNav+='<div class="container">';
topNav+='  <div class="logo">'; 
topNav+='    <!--logo Start-->'; 
topNav+='    <img src="images/logo-cap.jpg" width="197" height="48" alt=""/>'; 
topNav+='    <!--logo Ends--> ';
topNav+='  </div>';
topNav+='  <div class="main-nav">';
topNav+='    <nav>';
topNav+='      <ul>';
topNav+='        <li><a href="#">TDM Governance</a></li>';
topNav+='       <li><a href="./index" class="active">TDM Life Cycle</a></li>';
topNav+='       <li><a href="#">Command Center</a></li>';
topNav+='        <li><a href="#">Training</a></li>';
topNav+='      </ul>';
topNav+='   </nav>';
topNav+='    </div>';
topNav+='   <div class="clearfloat">&nbsp;</div>';
topNav+='  </div>';
topNav+='</div>';
topNav+='<div class="title-band">';
topNav+='<div class="container">';
topNav+='  <div class="title">';
topNav+='    <h3>TDM Central</h3>';
topNav+='  </div>';
topNav+='  <!-- Advanced Search Link -->';
topNav+='  <div class="advanced-search"><a href="./myReservationProv">My Reservations</a></div>';
topNav+='  <!-- /Advanced Search Link --> ';
topNav+=' <!-- Simple Navigation Menu for Quick Link -->';
topNav+='  <div class="quicklink-container">';
topNav+='    <div class="quicklink-sh"> <a href="#">Quick Link</a> </div>';
topNav+='    <div class="quicklink-list">';
topNav+='     <ul>';
topNav+='        <li><a href="#">TD Generator</a></li>';
topNav+='        <li><a href="#">Virtual University</a></li>';
topNav+='        <li><a href="#">Auto Email</a></li>';
topNav+='        <li><a href="#">LIVE</a></li>';
topNav+='        <li><a href="./testdaUser">Find Test Data</a></li>';
topNav+='        <li><a href="#">TDM Architecture</a></li>';
topNav+='      </ul>';
topNav+='    </div>';
topNav+='  </div>';
topNav+='  <!-- /Simple Navigation Menu for Quick Link -->';
topNav+='  <div class="clearfloat">&nbsp;</div>';
topNav+='</div>';
topNav+='</div>';
topNav+='</header>';
document.write(topNav);