var topNav='';
topNav+=' <section>';
topNav+='<nav class="mainTabCtrl clearfix">';
topNav+='	<ul>';
topNav+='		<li id="Policy_Search"><a href="./policySearch">Policy Search</a><span>Policy Search </span></li>';
topNav+='		<li id="Claim_Search"><a href="./claimSearch">Claim Search</a><span>Claim Search</span></li>';
topNav+='	</ul>';
topNav+='</nav>';
topNav+='   </section>';
document.write(topNav);