var topNav='';
topNav+='<header>';
topNav+=' <article class="top-blue-nav">'; 
topNav+='	  <section class="primary-nav">';
topNav+='       <nav>';
topNav+='        <ul>';
topNav+='			<li><a href="http://www.capgemini.com/about-capgemini" TARGET="_NEW"><img src="images/about-icon.png" width="20" height="20" alt=""/> About Us</a></li>';
topNav+='        	<li><a href="http://www.in.capgemini.com/contact-capgemini" TARGET="_NEW"><img src="images/contact-icon.png" width="20" height="20" alt=""/> Contact Us</a></li>';
topNav+='        </ul>';
topNav+='       </nav>';
topNav+='     </section>';
topNav+=' </article>';
topNav+=' <article class="navigation">';
topNav+='   <section class="logo"> ';
topNav+='    <img src="images/logo-cap.jpg" class="logo" alt=""/>'; 
topNav+='   </section>';
topNav+='  </article>';
topNav+=' <article class="title-band">';
topNav+='   <section class="title">';
topNav+='     <h3 class="h3Tdm" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h3>';
topNav+='   </section>';
topNav+=' </article>';
topNav+='</header>';
 
document.write(topNav);