var topNav='';
topNav+='<nav class="mainTabCtrl clearfix">';
topNav+='	<ul>';
topNav+='		<li id="Poly_Prop_Rev"><a href="./myReservationProp">Policy - Property Reservations</a><span>Policy - Property Reservations</span></li>';
topNav+='		<li id="Poly_Auto_Rev"><a href="./myReservationAuto">Policy - Auto Reservations</a><span>Policy - Auto Reservations</span></li>';
topNav+='		<li id="PolicySearch_Rev"><a href="./myReservationPolicy">Life - Policy Reservations</a><span>Life - Policy Reservations </span></li>';
topNav+='		<li id="ClaimSearch_Rev"><a href="./myReservationClaimSearch">Life - Claim Reservations</a><span>Life - Claim Reservations</span></li>';
topNav+='	</ul>';
topNav+='</nav>';
document.write(topNav);